import {
  FileText, Calculator, Users, Bot, UserCheck, HardHat, Briefcase,
  ClipboardList, Zap, Shield, Lock, Landmark, CreditCard, Layers,
  Sparkles, TrendingUp, Receipt, PenTool, Smartphone, Globe,
  BarChart3, Banknote, Brain, MessageSquare, PhoneCall, Mail,
  BookOpen, Calendar, Bell, BadgeCheck, Headphones, Star,
  CheckCircle, ArrowRight, ChevronDown, MapPin, Phone,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  FileText,
  Calculator,
  Users,
  Bot,
  UserCheck,
  HardHat,
  Briefcase,
  ClipboardList,
  Zap,
  Shield,
  Lock,
  Landmark,
  CreditCard,
  Layers,
  Sparkles,
  TrendingUp,
  Receipt,
  PenTool,
  Smartphone,
  Globe,
  BarChart3,
  Banknote,
  Brain,
  MessageSquare,
  PhoneCall,
  Mail,
  BookOpen,
  Calendar,
  Bell,
  BadgeCheck,
  Headphones,
  Star,
  CheckCircle,
  ArrowRight,
  ChevronDown,
  MapPin,
  Phone,
};
